title: Project
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        info:
          type: tab
          title: Info Box

          fields:
            header.info:
              type: editor
              label: Content

        gallery:
          type: tab
          title: Gallery

          fields:
            header.gallery:
              type: list
              style: vertical
              label: Images

              fields:
                .title:
                  type: text
                  size: medium
                  label: 'Title'
                  help: 'The image title'
                .image:
                  type: filepicker
                  folder: 'self@'
                  preview_images: true
                  accept:
                    - 'image/*'
                    - '.jpg'
                    - '.png'
                    - '.gif'
                  label: 'Image'
                  help: 'Select an image'
